### ISSUE TITLE
페이지 스타일링

### ISSUE THREAD

**Issue by arori** [3-advisor/seohyeonee-front#2]
### Page List
1. Main Page

### Requirement
* Restaurant
    * Random Pick
    * View List
    * Search
    * Register
* Random Pick?

### Data
* Restaurant
    * name
    * description
    * tags

**Comment by kimboha** [comment]
https://docs.google.com/presentation/d/1RYV-D8lzEcw92qVr_0mLnJ_JnriPX7lQOUh8TEwjaXE/edit?usp=sharing

**Comment by kimboha** [comment]
[seohyeonee front.pdf](https://github.com/3-advisor/seohyeonee-front/files/4119856/seohyeonee.front.pdf)
[seohyeonee front.pptx](https://github.com/3-advisor/seohyeonee-front/files/4119857/seohyeonee.front.pptx)
